# Generated by Django 3.0.7 on 2020-11-09 10:03

import WebApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField()),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpAge', models.IntegerField()),
                ('EmpRank', models.IntegerField()),
                ('Photo', models.ImageField(blank=True, null=True, upload_to=WebApp.models.Users.upload_photo)),
                ('resume', models.FileField(blank=True, null=True, upload_to=WebApp.models.Users.upload_photo)),
            ],
        ),
    ]
